openapi: 3.0.0
servers:
  - url: 'https://login.cp.gov.tw/v01/connect'
info:
  version: v01
  title: GSP登入授權
  description: 提供Mydata登入授權使用API規格
paths:
  /authorize:
    get:
      summary: SP登入驗證完成後導向redirect_uri
      description: SP登入驗證完成後導向redirect_uri
      parameters:
        - name: client_id
          in: query
          required: true
          schema:
            type: string
        - name: redirect_uri
          in: query
          required: true
          schema:
            type: string
        - name: response_mode
          in: query
          required: true
          schema:
            type: string
        - name: response_type
          in: query
          required: true
          schema:
            type: string
        - name: scope
          in: query
          required: true
          schema:
            type: string
        - name: nonce
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        '302':
          description: redirect_uri
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  code:
                    description: authorization code
                    type: string
                  id_token:
                    description: 'id token, 用來識別user身份'
                    type: string
                  scope:
                    description: 被許可的權限項目
                    type: string
                  nonce:
                    description: 請求時帶入的nonce參數
                    type: string
                  state:
                    description: 請求時帶入的state參數
                    type: string
                  session_state:
                    description: authorization server上的sessionId
                    type: string
  /token:
    post:
      summary: SP向授權主機請求access_token
      description: SP向授權主機請求access_token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              items:
                properties:
                  client_id:
                    description: SP服務端代號
                    type: string
                  client_secret:
                    description: SP服務端密鍵
                    type: string
                  grant_type:
                    description: >-
                      authorization_code(指定要求access_token)或
                      refresh_token(指定更新access_token)
                    type: string
                  code:
                    description: authorization code
                    type: string
                  redirect_uri:
                    description: 導向回到路徑
                    type: string
                  scope:
                    description: 授權範圍
                    type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id_token:
                      type: string
                      description: 'id token, 用來識別user身份'
                    access_token:
                      type: string
                      description: authorization access_token
                    expires_in:
                      type: string
                      description: 到期時間
                    token_type:
                      type: string
                      description: token_type
                    refresh_token:
                      type: string
                      description: 刷新用token
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /userinfo:
    get:
      summary: SP或DP 取得 user_info
      description: SP或DP 取得 user_info
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer +accessToken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    sub:
                      type: string
                      description: '與id_token相同, 用來識別user身份, AS使用者鍵值'
                    account:
                      type: string
                      description: egov帳號
                    uid:
                      type: string
                      description: 身份證字號
                    uid_verified:
                      type: string
                      description: 身份證字號是否已驗證
                    birthdate:
                      type: string
                      description: 生日
                    gender:
                      type: string
                      description: 性別
                    cn:
                      type: string
                      description: 姓名
                    email:
                      type: string
                      description: 電子郵件信箱
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /introspect:
    post:
      summary: DP反查access_token是否有效
      description: DP反查access_token是否有效
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: 'Basic (resourceId:resourceSecret 字串以Base64編碼)'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              items:
                properties:
                  token:
                    description: access_token
                    type: string
            
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    sub:
                      type: string
                      description: '與id_token相同, 用來識別user身份'
                    scope:
                      type: string
                      description: access_token授權範圍
                    clientId:
                      type: string
                      description: 登入的SP服務鍵值
        '401':
          description: Unauthorized
        '403':
          description: Forbidden